# %% [markdown]
# # **<span style="color: #87CEEB;">DCGAN: Latent Space Exploration</span>**
# 

# %% [markdown]
# ### Name Removed for Security

# %% [markdown]
# # DCGAN with Latent Space Interpolation and Exploration
# 
# In this experiment, I'll implement a Generative Adversarial Network (GAN) to:
# - Generate images resembling handwritten digits from the MNIST dataset.
# - Explore latent space interpolation between two images by transitioning from one digit to another.
# - Generate images and perform mathematical operations in the latent space to explore the output variations.

# %% [markdown]
# ### Imports

# %%
# ============ Import stuff here =============
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import torchvision.utils as vutils
import matplotlib.pyplot as plt
import numpy as np
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
# ===== you may include more helper libs ======
# ===== (just don't include an entire =========
# ===== generator/discriminator - that ========
# ===== you've to make from scratch) ==========
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from torch.utils.data import DataLoader, random_split

# %% [markdown]
# ### Load the MNIST thing

# %% [markdown]
# In this section:
# - Load the MNIST dataset
# - Transform/pre-process the dataset (if required)
# - Define your test-train split
# - Use dataloader to load stuff
# - Print the split ratio AND visualize some of the digits (along with the labels)

# %%

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

mnist_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)

train_ratio = 0.8
train_size = int(train_ratio * len(mnist_dataset))
test_size = len(mnist_dataset) - train_size
train_dataset, test_dataset = random_split(mnist_dataset, [train_size, test_size])

print("Train set size:", len(train_dataset))
print("Test set size:", len(test_dataset))
print("Train/Test split ratio: {:.2f}% / {:.2f}%".format(100 * len(train_dataset)/len(mnist_dataset),
                                                         100 * len(test_dataset)/len(mnist_dataset)))

batch_size = 128
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

def visualize_samples(dataset, num_samples=9):
    fig, axes = plt.subplots(3, 3, figsize=(8, 8))
    indices = torch.randperm(len(dataset))[:num_samples]
    for ax, idx in zip(axes.flatten(), indices):
        image, label = dataset[idx]
        image = image * 0.5 + 0.5
        ax.imshow(image.squeeze(), cmap='gray')
        ax.set_title(f"Label: {label}")
        ax.axis('off')
    plt.tight_layout()
    plt.show()

visualize_samples(train_dataset)

# %% [markdown]
# ## Make your GANg
# ![pic.png](attachment:pic.png)
# 
# Basic GAN structure is show above. GANs have two componenets:
# 
# **Generator (G):** Takes a random noise vector ($z$) as input and generates synthetic image $G(z)$ i.e., an output that aims to resemble real data.
# **Discriminator (D):** Acts as a binary classifier that distinguishes between real and fake image. It is trained to correctly identify whether an input is real (from the dataset) or fake (generated by G).
# 
# They both compete with each other. The generator tries to fool the discriminator, while the discriminator tries to improve its ability to detect fakes. This adversarial process helps the generator produce increasingly realistic outputs.

# %%
# Code the Generator here
class Generator(nn.Module):
    def __init__(self):
        self.noise_dim=100
        self.feature_dim=64
        self.out_channels=1

        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.ConvTranspose2d(self.noise_dim, self.feature_dim, kernel_size=7, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(self.feature_dim),
            nn.ReLU(True),
            nn.ConvTranspose2d(self.feature_dim, self.feature_dim // 2, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(self.feature_dim // 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(self.feature_dim // 2, self.out_channels, kernel_size=4, stride=2, padding=1, bias=False),
            nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)

# %%
# Code the Discriminator here
class Discriminator(nn.Module):
    def __init__(self, in_channels=1, feature_dim=64):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(

            nn.Conv2d(in_channels, feature_dim, kernel_size=4, stride=2, padding=1),

            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(feature_dim, feature_dim * 2, kernel_size=4, stride=2, padding=1),

            nn.BatchNorm2d(feature_dim * 2),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(feature_dim * 2, feature_dim * 4, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(feature_dim * 4),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(feature_dim * 4, 1, kernel_size=4, stride=1, padding=0),
            nn.Flatten(),
            nn.Sigmoid()
        )


    def forward(self, x):
        return self.model(x)

# %%
# initializing the instances of the Generator and Discriminator respectively
generator = Generator()
discriminator = Discriminator()

# %% [markdown]
# ### Losses and optimizers

# %%
# Loss
criterion = nn.BCELoss()

# Optimizers
optimizer_g = optim.Adam(generator.parameters(), lr=0.0002)
optimizer_d = optim.Adam(discriminator.parameters(), lr=0.0002)

# %% [markdown]
# ## Training Loop
# Now we have to load the data (preprocess it or do some image augmentation if you need) and train the model.
# 
# Lets have brief look at how the loop for a vanilla GAN looks like, and then you can implement it yourself.
# 
# Each epoch involves a couple of steps:
# 1. Prep some data both fake and real
# 2. Train the discriminator with some real data (real loss)
# 3. Train the discriminator with some fake data (fake loss)
# 4. Train the generator (generator loss)
# 
# details about losses is below

# %% [markdown]
# **Discriminator**
# The discriminator is trained to distinguish between real and fake images (binary classification). It aims to correctly classify real images as real and generated images as fake. It has two components:
# - Real Loss: Measures how well the discriminator classifies real images correctly.
# - Fake Loss: Measures how well the discriminator identifies fake images. <br> <br>
# The total discriminator loss is given by: <br>
# $ L_{D} =$ real loss $+$ fake loss <br>
# where <br>
# real loss $= E_{x}\log(D(x))$ <br>
# fake loss $= E_{z}\log(1-D(G(z)))$
# 

# %% [markdown]
# **Generator**
# The generator tries to fool the discriminator by generating images that D misclassifies as real. Instead of minimizing the difference between generated and real images directly, G is trained to maximize the likelihood that $D$ assigns high probability to fake images (so it'll only have the maximizing portion) <br><br>
# $ L_{G} = E\log(D(G(z)))$  <br>

# %%
epochs = 30
noise_dim = 100

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
generator.to(device)
discriminator.to(device)

# Training Loop
train_d_losses = []
train_g_losses = []

best_g_loss = float('inf')
best_gen_state = None
best_disc_state = None

for epoch in range(epochs):
    generator.train()
    discriminator.train()
    epoch_d_loss = 0.0
    epoch_g_loss = 0.0
    num_batches = 0

    for batch_idx, (real_images, _) in enumerate(train_loader):
        real_images = real_images.to(device)
        current_batch_size = real_images.size(0)
        num_batches += 1

        real_labels = torch.ones(current_batch_size, 1, device=device)
        fake_labels = torch.zeros(current_batch_size, 1, device=device)

        optimizer_d.zero_grad()

        outputs_real = discriminator(real_images)
        loss_real = criterion(outputs_real, real_labels)

        noise = torch.randn(current_batch_size, noise_dim, 1, 1, device=device)
        fake_images = generator(noise)

        outputs_fake = discriminator(fake_images.detach())
        loss_fake = criterion(outputs_fake, fake_labels)

        d_loss = loss_real + loss_fake
        d_loss.backward()
        optimizer_d.step()

        optimizer_g.zero_grad()

        noise = torch.randn(current_batch_size, noise_dim, 1, 1, device=device)
        fake_images = generator(noise)
        outputs = discriminator(fake_images)

        g_loss = criterion(outputs, real_labels)
        g_loss.backward()
        optimizer_g.step()

        epoch_d_loss += d_loss.item()
        epoch_g_loss += g_loss.item()

    avg_d_loss = epoch_d_loss / num_batches
    avg_g_loss = epoch_g_loss / num_batches
    train_d_losses.append(avg_d_loss)
    train_g_losses.append(avg_g_loss)

    print(f"Epoch [{epoch+1}/{epochs}]  D Loss: {avg_d_loss:.4f}  G Loss: {avg_g_loss:.4f}")

    if avg_g_loss < best_g_loss:
        best_g_loss = avg_g_loss
        best_gen_state = generator.state_dict()
        best_disc_state = discriminator.state_dict()
        print(f"--> New best models found at epoch {epoch+1}")

    if (epoch + 1) % 10 == 0:
        with torch.no_grad():
            noise = torch.randn(16, noise_dim, 1, 1, device=device)
            sample_images = generator(noise).cpu()
            grid = vutils.make_grid(sample_images, normalize=True)
            plt.figure(figsize=(6,6))
            plt.imshow(grid.permute(1, 2, 0))
            plt.title(f"Epoch {epoch+1}")
            plt.axis('off')
            plt.show()

# %% [markdown]
# ### Display Statistics and Visualize Best Generator
# 1. Save the best generator and discriminator models.
# 2. Plot discriminator and generator losses.
# 3. Visualize an image from the best generator.

# %%
# code
torch.save(best_gen_state, "vae_generator.pth")
torch.save(best_disc_state, "vae_discriminator.pth")
print("Best generator and discriminator models saved.")

plt.figure(figsize=(10, 5))
plt.plot(train_d_losses, label="Discriminator Loss")
plt.plot(train_g_losses, label="Generator Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.title("Training Losses")
plt.show()

best_generator = Generator().to(device)
best_generator.load_state_dict(torch.load("vae_generator.pth"))
best_generator.eval()

with torch.no_grad():
    noise = torch.randn(1, noise_dim, 1, 1, device=device)
    generated_image = best_generator(noise).cpu()

generated_image = (generated_image * 0.5) + 0.5

plt.figure(figsize=(4, 4))
plt.imshow(generated_image.squeeze(), cmap='gray')
plt.title("Image from Best Generator")
plt.axis("off")
plt.show()

# %% [markdown]
# ### Latent space interpolation with MNIST
# The latent space is the space of all possible inputs that the generator can take, and it is a vector space, and since it is a vector space we can do some vector operations on it, such as interpolation, which is what we will be doing here.
# To read up more on this, you can visit the following link: https://machinelearningmastery.com/how-to-interpolate-and-perform-vector-arithmetic-with-faces-using-a-generative-adversarial-network/
# 

# %% [markdown]
# ### Exploration Tasks:
# 1. Define two random noises of some latent dimensions.
# 2. Generate images by interpolating from one noise to the other using linear interpolation:  
#    
#    $$
#    \text{interpolation} = \alpha \cdot z_1 + (1-\alpha) \cdot z_2
#    $$  
# 
#    where  $z_{1}$ and $z_{2}$ are two random noises in the latent space. The result should be a series of images showing the transition.
# 
# 3. Visualize the interpolated generation with at least 10 steps.
# 

# %%
# code here

z1 = torch.randn(1, noise_dim, 1, 1, device=device)
z2 = torch.randn(1, noise_dim, 1, 1, device=device)

generator.eval()

num_steps = 10
alphas = torch.linspace(0, 1, steps=num_steps)

interpolated_images = []
for alpha in alphas:
    interpolated_noise = alpha * z1 + (1 - alpha) * z2
    with torch.no_grad():
        generated = generator(interpolated_noise)
    generated = (generated * 0.5) + 0.5
    interpolated_images.append(generated.squeeze(0).cpu())

interpolated_images = torch.stack(interpolated_images)
grid = vutils.make_grid(interpolated_images, nrow=num_steps, normalize=True)

plt.figure(figsize=(15, 5))
plt.imshow(grid.permute(1, 2, 0))
plt.title("Latent Space Interpolation")
plt.axis("off")
plt.show()


# %% [markdown]
# ### Latent Space Interpolation with CelebA Dataset
# `CelebA` dataset contains ~200,000 images of 178×218 celebrity faces. Using a pre-trained generator to explore latent space interpolation.

# %%
# put the dcgan.py file and generator.pt in the current directory and then run this cell
from dcgan import DCGAN
generator_path = "generator.pt"
gan = DCGAN(gan_type="gan", use_cuda=True)
gan.load_model(filename=generator_path, use_cuda=torch.cuda.is_available())
gan.eval()
gan = gan.to(device)
print("Number of parameters in the pre-trained generator:", gan.get_num_params())
gan = gan.cuda()  # Move to GPU if available

# %%
'''
Exploration Steps:
1- Visualize the images generated from z1 and z2
2- Interpolate from z1 to z2 and visualize all interpolation steps
3- Ensure interpolation has minimum of 10 steps.
'''

# ====== Your code below ========
z1 = torch.randn(1, gan.latent_dim, device=device)
z2 = torch.randn(1, gan.latent_dim, device=device)

with torch.no_grad():
    img_z1 = gan.G(z1).cpu()
    img_z2 = gan.G(z2).cpu()

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
axes[0].imshow(vutils.make_grid(img_z1, normalize=True).permute(1, 2, 0).squeeze())
axes[0].set_title("Image from z1")
axes[0].axis("off")

axes[1].imshow(vutils.make_grid(img_z2, normalize=True).permute(1, 2, 0).squeeze())
axes[1].set_title("Image from z2")
axes[1].axis("off")
plt.show()

alphas = torch.linspace(0, 1, steps=num_steps, device=device)

interpolated_images = []
with torch.no_grad():
    for alpha in alphas:
        z_interp = alpha * z1 + (1 - alpha) * z2
        img_interp = gan.G(z_interp).cpu()
        interpolated_images.append(img_interp)

interpolated_images = torch.cat(interpolated_images, dim=0)

grid = vutils.make_grid(interpolated_images, nrow=num_steps, normalize=True)
plt.figure(figsize=(20, 4))
plt.imshow(grid.permute(1, 2, 0).squeeze())
plt.title("Latent Space Interpolation (10 steps) from z1 to z2")
plt.axis("off")
plt.show()
# ====== Your code above ========


# %% [markdown]
# ### Vector Arithmetic in the Latent Space
# Since the latent space is a vector space, arithmetic operations (addition, subtraction, etc.) can be performed.

# %% [markdown]
# When interpolating between two CelebA images in the latent space, the transition sometimes passes through representations of other facial expressions or genders. This happens because the latent space captures underlying features of the dataset, and the interpolation path can traverse regions where features mix.
# 
# This concept extends to arithmetic in the latent space—adding/subtracting latent vectors can produce meaningful blends of their features.
# 
# Exploration tasks:
# 1. Generate two or more images.
# 2. Perform arithmetic on their latent space vectors and generate the resultant image.
# 3. Display the results.
# 
# ### Example:
# 1. $\text{random\_noise}_1$ generates $\text{generated\_image}_1$, and $\text{random\_noise}_2$ generates $\text{generated\_image}_2$.
# 2. Compute: $\text{random\_noise}_r$ = $\text{random\_noise}_1$ + $\text{random\_noise}_2$
# 3. Generate an image from $\text{random\_noise}_r$, denoted as $\text{generated\_image}_r$.
# 4. Display the results.
# 
# Repeat for at least three different pairs with different arithmetic operations.

# %%
# Display random images from the generator, then display their arithmetic results.

num_pairs = 3
fig, axes = plt.subplots(num_pairs, 3, figsize=(12, 4 * num_pairs))

for i in range(num_pairs):
    noise1 = torch.randn(1, gan.latent_dim, device=device)
    noise2 = torch.randn(1, gan.latent_dim, device=device)

    torch.save(noise1, f"noise1_pair_{i+1}.pt")
    torch.save(noise2, f"noise2_pair_{i+1}.pt")

    with torch.no_grad():
        image1 = gan.G(noise1).cpu()
        image2 = gan.G(noise2).cpu()

    noise_r = noise1 + noise2
    with torch.no_grad():
        image_r = gan.G(noise_r).cpu()

    axes[i, 0].imshow(vutils.make_grid(image1, normalize=True).permute(1, 2, 0).squeeze())
    axes[i, 0].set_title("Image from z1")
    axes[i, 0].axis("off")

    axes[i, 1].imshow(vutils.make_grid(image2, normalize=True).permute(1, 2, 0).squeeze())
    axes[i, 1].set_title("Image from z2")
    axes[i, 1].axis("off")

    axes[i, 2].imshow(vutils.make_grid(image_r, normalize=True).permute(1, 2, 0).squeeze())
    axes[i, 2].set_title("Arithmetic: z1 + z2")
    axes[i, 2].axis("off")

plt.tight_layout()
plt.show()


# %% [markdown]
# ## OBSERVATIONS

# %% [markdown]
# **Q1:** Some generated images appear distorted or unrealistic. What major factors might cause this distortion in GANs? <br><br>
# **Observations**:
# - Training Instability -> since GANs are very sensitive to changes during traning, this leads to unstable convergence and distorted outputs.
# - Mode Collapse -> generator might focus on producing a limited set of outputs, causing unrealistic and repetitive images.

# %% [markdown]
# Further reading on how diffusion models introduced improved realism in image generation compared to GANs: https://aurorasolar.com/blog/putting-ai-to-the-test-generative-adversarial-networks-vs-diffusion-models/


